[package]
name = "my_rust_module"
version = "0.1.0"
edition = "2021"

# [[bin]]
# name = "svm_benchmark"
# path = "src/bin/svm_benchmark.rs"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { version = "0.21", features = ["extension-module"] }
rand = "0.8"
numpy = "0.21.0"
rayon = "1.5"
ndarray = { version = "0.15", features = ["rayon"] }
ndarray-parallel = "0.9.1"
faer = { version = "0.22.6", features = ["std"] }
lru = "0.12"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
overflow-checks = false
incremental = false

[profile.release-generic]
inherits = "release"
target-cpu = "x86-64-v3"

[profile.bench]
inherits = "release"
debug = true

[build-dependencies]
cc = "1.0"
